from provasOrais.views.home import *
from provasOrais.views.alunos import *
from provasOrais.views.assuntos import *
from provasOrais.views.disciplinas import *
from provasOrais.views.perguntas import *
from provasOrais.views.questoes import *
from provasOrais.views.turmas import *
from provasOrais.views.usuario import *
from provasOrais.views.provas import *